spring:
  datasource:
    url: jdbc:mysql://${DATABASE_URL}/${DATABASE_SCHEMA}?serverTimezone=Asia/Seoul
    username:
    password:
  h2:
    console:
      enabled: false # H2 console ????
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect